### PR TITLE
Use meson build system

### PR DESCRIPTION
**Pull request by ecdye**
Signed-off-by: Ethan Dye <mrtops03@gmail.com

### CODE REVIEW

**Comment by UVV-gh** [comment]
I actually wanted to get rid of Makefile in favor of meson. Would you like to introduce meson instead of tweaking the makefile? I would assume it would fix many more use cases

**Comment by ecdye** [comment]
> I actually wanted to get rid of Makefile in favor of meson. Would you like to introduce meson instead of tweaking the makefile? I would assume it would fix many more use cases

I like the idea, I'm not super familiar with meson, but I'll look into it and try and get it working and see if I can update this PR with that instead. No promises, but it should be a fun challenge.

**Comment by UVV-gh** [comment]
I think we are on the right track! Thank you for your work, A few things that stand out and need rework:

- [x] We should include a sample README.md with a few instructions how to build it, e.g. a few paragraphs from [here](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Quick-guide.md) . We should note, that minimum required version for this is 0.54, because before that `meson compile` didn't exist
- [x] Makefile should go away
- [x] Binary targets should be marked as installable (`install : true`)
- [x] `meson test` currently fails. Either because it requires interactive `sudo` or relative path issue.
- [x] I'm not sure I like to have distro specifics here (talking about 'alpine' check), because of tons of different configurations. For example, this is how I handle it [open-embedded](https://github.com/openembedded/meta-openembedded/blob/master/meta-filesystems/recipes-utils/overlayfs/overlayfs-tools_git.bb), by storing the distro configuration required in the dedicated repository. Can we solve it differently? Does Alpine have it's own configuration like Yocto or Ubuntu/Debian? Let me also check if `musl` get linked against automatically in Yocto too after switching to meson...

**Comment by UVV-gh** [comment]
I hope this patch should do the trick for musl based builds and address the last item on my list, please give it a try:
```diff
diff --git a/meson.build b/meson.build
index 7397502..e479852 100644
--- a/meson.build
+++ b/meson.build
@@ -5,15 +5,14 @@ overlay_src = ['main.c', 'logic.c', 'sh.c']
 fsck_src = ['fsck.c', 'common.c', 'lib.c', 'check.c', 'mount.c', 'path.c', 'overlayfs.c']
 
 # Dependencies for executables
-overlay_dep = dependency('', required : false)
-if host_machine.system() in ['alpine']
-  overlay_dep = dependency('musl-fts')
-endif
+# We have to link against fts on musl based systems, but this is a soft dependency
+# If it's not found on the glibc systems, it's just ignored
+musl_fts = dependency('musl-fts', method : 'pkg-config', required : false)
 fsck_dep = meson.get_compiler('c').find_library('m', required : false)
 
 # Executables
-overlay = executable('overlay', overlay_src, dependencies : overlay_dep)
-executable('fsck.overlay', fsck_src, dependencies : fsck_dep)
+overlay = executable('overlay', overlay_src, dependencies : musl_fts)
+executable('fsck.overlay', fsck_src, dependencies : [fsck_dep, musl_fts])

```

**Comment by ecdye** [comment]
Alright, I think I've addressed all your concerns. Take a look, and let me know what you think!

**Comment by UVV-gh** [comment]
Looks very nice, thanks again for your work. I'm not sure that mentioning chatgpt is really needed in the commit message. Let's please remove it and we can merge.

**Comment by ecdye** [comment]
Done

**Review by UVV-gh — APPROVED** [review]

**Pull request merged**
