### PR TITLE
Add option to always continue when mounted

### PR DESCRIPTION
**Pull request by ecdye**
Signed-off-by: Ethan Dye <mrtops03@gmail.com>

### CODE REVIEW

**Comment by UVV-gh** [comment]
Thanks for the patch. The implementation looks good, but the options name is not really obvious. Shall we go for `-i` and `--ignore-mounted` instead?

What is your use case for that? I mean the results for mounted/unmouned fs could differ.

**Comment by ecdye** [comment]
> Thanks for the patch. The implementation looks good, but the options name is not really obvious. Shall we go for `-i` and `--ignore-mounted` instead?

I like it, I'll make the change

> What is your use case for that? I mean the results for mounted/unmouned fs could differ.

Occasionally I run into issues where the filesystem won't unmount because of broken open files (which yes is a bug in other programs) but I need it to at least try to sync down the changes before a reboot of a zram folder. I have an out of date implementation of this in ecdye/zram-config. I'm planning on updating it to use a submodule of this project instead now that it is actively being maintained again.

**Comment by UVV-gh** [comment]
Looks good. Please rebase leaving only one commit (no temporary fixes) and we can merge

**Comment by ecdye** [comment]
Done

**Review by UVV-gh — APPROVED** [review]

**Pull request merged**
